export type { IDataProcessor } from './IDataProcessor'
export type { IModule } from './IModule'
export type { IRLEDecoder } from './IRLEDecoder'
export type { IServerCutTextHandler } from './IServerCutTextHandler'
export type { IStateProcessor } from './IStateProcessor'
export type { ICommunicator, IKvmDataCommunicator } from './ICommunicator'
